{% set name = "jupytercad-freecad" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupytercad_freecad-{{ version }}.tar.gz
  sha256: 24df9df19715c4a40b8c95dca29426b572269e8d4107b80376b8cd1f9fbdbb07

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - yarn
    - jupyterlab >=4,<5
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2
  run:
    - python >=3.8
    - jupyter_ydoc >=3,<4
    - jupytercad_core >=3,<4
    - freecad <1

test:
  imports:
    - jupytercad_freecad
  requires:
    - pip
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-freecad/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-freecad\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupytercad/jupytercad-freecad
  summary: 'JupyterCAD plugin adding support for .fcstd files'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/jupytercad/jupytercad-freecad

extra:
  recipe-maintainers:
    - martinRenou
    - trungleduc
